global:
  scrape_interval: 15s # 메트릭을 수집할 주기
  evaluation_interval: 15s # alert에 대한 rule 을 평가하는 주기

scrape_configs:
  # - job_name: Node exporter
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #       - {ip_v4_address}:9100
  
  # https://github.com/prometheus-community/windows_exporter/releases/tag/v0.24.0 (windows_exporter)
  # - job_name: Windows exporter
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #         - {ip_v4_address}:9182

  - job_name: kafka-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - {ip_v4_address}:9308