global:
  scrape_interval: 15s # 메트릭을 수집할 주기
  evaluation_interval: 15s # alert에 대한 rule 을 평가하는 주기

scrape_configs:
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets:
        - {ip v4 address}:9100